global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'devops-ai-platform'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['localhost:9093']

# Rule files
# rule_files:
#   - 'alerts/*.yml'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js Backend Metrics
  - job_name: 'node-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'node-backend'
          environment: 'development'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Python Backend Metrics
  - job_name: 'python-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'python-backend'
          environment: 'development'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'
          environment: 'development'
    scrape_interval: 15s
